#!/bin/bash
set -eu

image_name="ubuntu-bionic-nowhere"
docker build -t "$image_name" .
docker run \
    -it \
    --privileged \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /dev:/dev \
    -v "$(pwd):/nowhere" \
    "$image_name"
