#!/bin/bash
set -eu

image_name="ubuntu-bionic-nowhere"
docker build \
    --build-arg USER_ID=$(id -u ${USER}) \
    --build-arg GROUP_ID=$(id -g ${USER}) \
    -t "$image_name" .
docker run \
    -it \
    --privileged \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /dev:/dev \
    -v "$(pwd):/nowhere" \
    "$image_name"
