#!/bin/bash
set -eu

IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
xhost + $IP

image_name="ubuntu-bionic-nowhere"
docker build \
    --build-arg USER_ID=$(id -u ${USER}) \
    --build-arg GROUP_ID=$(id -g ${USER}) \
    -t "$image_name" .
docker run \
    -it \
    --privileged \
    -e DISPLAY=$IP:0 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /dev:/dev \
    -v "$(pwd):/nowhere" \
    "$image_name"
